# Generated by Django 4.2.6 on 2023-10-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_post_comments_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(upload_to='media/image', verbose_name='Изображение'),
        ),
    ]
