# Generated by Django 4.2.6 on 2023-10-16 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=8000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(upload_to='media/image/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
