# Generated by Django 4.2.6 on 2023-10-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_description_alter_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name=''),
        ),
    ]
